### PR TITLE
feat: version update script

### PR DESCRIPTION
**Pull request by karannakra**

### CODE REVIEW

**Comment by JLarky** [comment]
This "works"; if I change `print(line, end="")` it will not mess up with the code as much, but it will still require running `yarn fmt` after running this script.

Suggestions:
- create `scripts` folder and put the file there
- fix `print(line, end="")`
- add this script to `release` script after `install` and before `fmt`

**Comment by karannakra** [comment]
acknowledged

**Comment by karannakra** [comment]
> This "works"; if I change `print(line, end="")` it will not mess up with the code as much, but it will still require running `yarn fmt` after running this script.
> 
> Suggestions:
> 
> * create `scripts` folder and put the file there
> * fix `print(line, end="")`
> * add this script to `release` script after `install` and before `fmt`

Done

**Comment by JLarky** [comment]
great! looks much better. So API is `<fogbender-simple-widget />` or `<fogbender-provider><fogbender-widget /><fogbender-provider>` not simple widget inside of provider :)

**Comment by JLarky** [comment]
Okay, let's see if that will actually run :) I don't know if python is installed in `changesets/action@v1`. If not, we can just run the script manually for now :)

**Comment by JLarky** [comment]
Great! it worked https://github.com/fogbender/fogbender-oss/actions/runs/3167077350/jobs/5157367257#step:6:29

**Pull request merged**
